# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HU_ratio_nodule_progression_detection_slice_cpp <- function(A1_slice, A2_slice, anno_i, anno_j, nodule_block_list_slice, split_num, block_num, detection_threshold) {
    .Call('_NPDS4Clib_HU_ratio_nodule_progression_detection_slice_cpp', PACKAGE = 'NPDS4Clib', A1_slice, A2_slice, anno_i, anno_j, nodule_block_list_slice, split_num, block_num, detection_threshold)
}

bwlabel <- function(x) {
    .Call('_NPDS4Clib_bwlabel', PACKAGE = 'NPDS4Clib', x)
}

get_border_indices <- function(labels, borders) {
    .Call('_NPDS4Clib_get_border_indices', PACKAGE = 'NPDS4Clib', labels, borders)
}

create_label_mask <- function(indices, borders_indices) {
    .Call('_NPDS4Clib_create_label_mask', PACKAGE = 'NPDS4Clib', indices, borders_indices)
}

create_clear_mask <- function(labels, label_mask) {
    .Call('_NPDS4Clib_create_clear_mask', PACKAGE = 'NPDS4Clib', labels, label_mask)
}

clear_border_pixels <- function(out, mask, bgval) {
    .Call('_NPDS4Clib_clear_border_pixels', PACKAGE = 'NPDS4Clib', out, mask, bgval)
}

clear_border <- function(labels, buffer_size = 0L, bgval = 0) {
    .Call('_NPDS4Clib_clear_border', PACKAGE = 'NPDS4Clib', labels, buffer_size, bgval)
}

generate_lung_tissue_blocks_slice_cpp <- function(image_slice, image_size, split_size) {
    .Call('_NPDS4Clib_generate_lung_tissue_blocks_slice_cpp', PACKAGE = 'NPDS4Clib', image_slice, image_size, split_size)
}

generate_nodule_block_list_slice_cpp <- function(image_slice, image_reg_slice, x_start, x_end, y_start, y_end, split_size) {
    .Call('_NPDS4Clib_generate_nodule_block_list_slice_cpp', PACKAGE = 'NPDS4Clib', image_slice, image_reg_slice, x_start, x_end, y_start, y_end, split_size)
}

generate_nodule_block_list_slice_cpp_v2 <- function(image_slice, image_reg_slice, x_start, x_end, y_start, y_end, split_size) {
    .Call('_NPDS4Clib_generate_nodule_block_list_slice_cpp_v2', PACKAGE = 'NPDS4Clib', image_slice, image_reg_slice, x_start, x_end, y_start, y_end, split_size)
}

process_lung_regions <- function(label_image, regions) {
    .Call('_NPDS4Clib_process_lung_regions', PACKAGE = 'NPDS4Clib', label_image, regions)
}

regionprops_bbox <- function(input) {
    .Call('_NPDS4Clib_regionprops_bbox', PACKAGE = 'NPDS4Clib', input)
}

trapz_rcpp <- function(x, y) {
    .Call('_NPDS4Clib_trapz_rcpp', PACKAGE = 'NPDS4Clib', x, y)
}

